import os


COMMIT_DATA_DIR = "commit_data"
DOCKER_IMAGE_NAME = "vfdetector-extended"
DOCKER_CONTAINER_NAME = "vfdetector-container"
VFDETECTOR_DOCKER_DIR = "/VFDetector"
INPUT_DIR = "input"
OUTPUT_DIR = "output"
VFDETECTOR_RESULT_DIR = "vfdetector_result"
REPOSITORY_DIR = "repository"
STATIC_ANALYZER_TOOL_REPORT_DIR = "{tool}_report"
WARNING_DATABASE_DIR = "warning_database"
TEMP_DIR = "tmp"

BASE_PATH = os.path.dirname(os.path.abspath(__file__))

TEMP_DIR_PATH = os.path.join(BASE_PATH, TEMP_DIR)

COMMIT_DATA_DIR_PATH = os.path.join(TEMP_DIR_PATH, COMMIT_DATA_DIR)

REPOSITORY_DIR_PATH = os.path.join(TEMP_DIR_PATH, REPOSITORY_DIR)

VFDETECTOR_RESULT_DIR_PATH = os.path.join(TEMP_DIR_PATH, VFDETECTOR_RESULT_DIR)

STATIC_ANALYZER_TOOL_REPORT_DIR_PATH = os.path.join(
    TEMP_DIR_PATH, STATIC_ANALYZER_TOOL_REPORT_DIR
)

WARNING_DATABASE_DIR_PATH = os.path.join(BASE_PATH, WARNING_DATABASE_DIR)

PROJECT_COMMIT_DATA_DIR_PATH = os.path.join(COMMIT_DATA_DIR_PATH, "{project_name}")

PROJECT_COMMIT_DATA_INPUT_DIR_PATH = os.path.join(
    PROJECT_COMMIT_DATA_DIR_PATH, INPUT_DIR
)

PROJECT_COMMIT_DATA_OUTPUT_DIR_PATH = os.path.join(
    PROJECT_COMMIT_DATA_DIR_PATH, OUTPUT_DIR
)

PROJECT_REPOSITORY_DIR_PATH = os.path.join(REPOSITORY_DIR_PATH, "{project_name}")

PROJECT_VFDETECTOR_RESULT_DIR_PATH = os.path.join(
    VFDETECTOR_RESULT_DIR_PATH, "{project_name}"
)

PROJECT_STATIC_ANALYZER_TOOL_REPORT_DIR_PATH = os.path.join(
    STATIC_ANALYZER_TOOL_REPORT_DIR_PATH, "{project_name}"
)

PROJECT_WARNING_DATABASE_DIR_PATH = os.path.join(
    WARNING_DATABASE_DIR_PATH, "{project_name}"
)
